# Generated by Django 5.0.3 on 2024-03-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video', models.FileField(default='', upload_to='videos/')),
                ('videoID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
